/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalibrateIdRouteImport } from './routes/calibrate.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrateIdRoute = CalibrateIdRouteImport.update({
  id: '/calibrate/$id',
  path: '/calibrate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/calibrate/$id': typeof CalibrateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/calibrate/$id': typeof CalibrateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/calibrate/$id': typeof CalibrateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/custom' | '/history' | '/settings' | '/calibrate/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/custom' | '/history' | '/settings' | '/calibrate/$id'
  id: '__root__' | '/' | '/custom' | '/history' | '/settings' | '/calibrate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomRoute: typeof CustomRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  CalibrateIdRoute: typeof CalibrateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibrate/$id': {
      id: '/calibrate/$id'
      path: '/calibrate/$id'
      fullPath: '/calibrate/$id'
      preLoaderRoute: typeof CalibrateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomRoute: CustomRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  CalibrateIdRoute: CalibrateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
